### ISSUE TITLE
New check system seems to be case-sensitive

### ISSUE THREAD

**Issue by rozzingit** [Arx-Game/arxcode#339] opened 2020-10-04 22:26 UTC
This might be fixed with #330, but I think it's more of a bug: right now the stat and skill values in the new check system SEEM to possibly be case-sensitive. The results from capitalizing your stat+skill combo (`check Charm+Seduction`) are wildly different from checking them lowercase (`check charm+seduction`). Pretty sure that lowercase is what it recognizes as being the stats and skills on your sheet. So if that's the case, definitely something to fix on the sooner end of things with the new system.

**Comment by somethingfinite** [comment] 2020-10-04 23:46
Had the same experience.

**Comment by TehomCD** [comment] 2020-10-05 22:47
Yeah, duplicate of #330

**Closed as completed by TehomCD** 2020-10-05 22:47 UTC
